SIGINT-1663:  Jenkins - Avoid passing empty values to synopsys bridge, if the values are not set
jenkinsci/synopsys-security-scan-plugin pull request #105
Opened 2024-03-20 05:42 UTC by maksudur-rahman-maruf

2024-03-25 09:20 UTC, zaman-akib requested changes

2024-03-25 09:20 UTC, zaman-akib commented on src/main/java/io/jenkins/plugins/synopsys/security/scan/service/scan/blackduck/BlackDuckParametersService.java
>              blackDuck.getAutomation().setFixpr(Boolean.parseBoolean(value));
Can be refactored to - 
```
automation.setFixpr(Boolean.parseBoolean(value));
blackDuck.setAutomation(automation);
```

2024-03-25 09:20 UTC, zaman-akib commented on src/main/java/io/jenkins/plugins/synopsys/security/scan/service/scan/blackduck/BlackDuckParametersService.java
>              blackDuck.getAutomation().setPrComment(Boolean.parseBoolean(value));
Can be refactored to - 
```
automation.setPrComment(Boolean.parseBoolean(value));
blackDuck.setAutomation(automation);
```

2024-03-25 09:20 UTC, zaman-akib commented on src/main/java/io/jenkins/plugins/synopsys/security/scan/service/scan/blackduck/BlackDuckParametersService.java
> +                blackDuck.getScan().getFailure().setSeverities(failureSeverities);
Can be refactored to - 
```
Failure failure = new Failure();
failure.setSeverities(failureSeverities);
scan.setFailure(failure);
blackDuck.setScan(scan);
```

2024-03-25 09:20 UTC, zaman-akib commented on src/main/java/io/jenkins/plugins/synopsys/security/scan/service/scan/coverity/CoverityParametersService.java
> +                        coverity.getConnect().getPolicy().setView(value);
refactor this to have the consistency, also check the below `cases`

2024-03-27 06:30 UTC, zaman-akib approved these changes

2024-03-29 10:48 UTC, jahid1209 approved these changes

2024-04-17 08:50 UTC, merged