Added jenkins credentials provider instructions on the readme
jenkinsci/synopsys-security-scan-plugin pull request #16
Opened 2023-10-25 15:06 UTC by maksudur-rahman-maruf

- As we have replaced few secret fields such as password, token with Jenkins Credentials Provider under the synopsys security sections of the global ui.
- Now we updated the instructions in the readme according to the change of those secret fields.

2023-10-25 22:30 UTC, kishorikumar requested changes

2023-10-25 22:30 UTC, kishorikumar commented on README.md
> +>- First you need to click on the add button. Then click Jenkins item on the dropdown.
If user have already added secrets using (Manage Jenkins -> Credentials) will be listed in the drop down and user can select it.

2023-10-26 07:29 UTC, jahid1209 approved these changes

2023-10-26 07:33 UTC, zaman-akib approved these changes

2023-10-27 08:31 UTC, merged