SIGINT-2205:  [Deprecate] [Jenkins]: synopsys-security-scan plugin
jenkinsci/synopsys-security-scan-plugin pull request #186
Opened 2024-11-22 09:18 UTC by maksudur-rahman-maruf

- Added a deprecation message to the log.
- Added a deprecation message to the README.
- Updated the global config title to include [DEPRECATED].
- Updated the application name to include [DEPRECATED]

2024-11-22 11:06 UTC, jahid1209 commented
Add the 'Deprecated' label in the [index.jelly](https://github.com/jenkinsci/synopsys-security-scan-plugin/blob/SIGINT-2205/src/main/resources/index.jelly) file

2024-11-22 11:11 UTC, jahid1209 requested changes
Add the 'Deprecated' label in the [index.jelly](https://github.com/jenkinsci/synopsys-security-scan-plugin/blob/SIGINT-2205/src/main/resources/index.jelly) file

2024-11-22 12:52 UTC, jahid1209 approved these changes

2024-11-25 12:30 UTC, zaman-akib requested changes
TODO: add "deprecated" topic in repository once we decide to merge this MR.

2024-12-02 06:27 UTC, closed without merging