SIGINT-1198 SARIF report generation for BLACKDUCK
jenkinsci/synopsys-security-scan-plugin pull request #57
Opened 2024-01-11 07:25 UTC by sadmananik

2024-01-15 09:37 UTC, jahid1209 requested changes

2024-01-15 09:37 UTC, jahid1209 commented on src/main/java/io/jenkins/plugins/synopsys/security/scan/SecurityScanner.java
> +                        ReportType.SARIF);
Line 109-123 can be simplified like below:
 ```
    String reportFilePath = customSarifReportFilePath != null ? customSarifReportFilePath : defaultSarifReportFilePath;

    UploadReportService uploadReportService = new UploadReportService(
            run,
            listener,
            launcher,
            envVars,
            new ArtifactArchiver(new File(reportFilePath).getName()));

    uploadReportService.archiveReports(workspace.child(reportFilePath), ReportType.SARIF);

2024-01-15 09:37 UTC, jahid1209 commented on src/main/java/io/jenkins/plugins/synopsys/security/scan/SecurityScanner.java
> +                String defaultSarifReportFilePath = isBlackDuckScan
Add a blank line here to improve readability.

2024-01-15 09:37 UTC, jahid1209 commented on src/main/resources/io/jenkins/plugins/synopsys/security/scan/extension/pipeline/SecurityScanStep/help-blackduck_reports_sarif_file_path.html
> +    File path including file name where SARIF report should be created(need to include file name as well)
Add a blank space after 'created' and before '('

2024-01-15 09:37 UTC, jahid1209 commented on src/main/resources/io/jenkins/plugins/synopsys/security/scan/extension/pipeline/SecurityScanStep/help-polaris_reports_sarif_create.html
> +</div>
Remove all Polaris specific input fields in the pipeline syntax.

2024-01-15 09:39 UTC, jahid1209 commented on src/main/java/io/jenkins/plugins/synopsys/security/scan/service/ScannerArgumentService.java
> +    public Sarif prepareSarifObject(Set<String> securityProducts, Map<String, Object> scanParameters) {
Write unit tests for this method for code coverage.

2024-01-17 11:00 UTC, jahid1209 approved these changes

2024-02-23 09:51 UTC, jahid1209 requested changes

2024-02-23 09:51 UTC, jahid1209 commented on src/main/java/io/jenkins/plugins/synopsys/security/scan/SecurityScanner.java
> +                                + ApplicationConstants.SARIF_REPORT_FILENAME
use concat like this:
```
 ApplicationConstants.DEFAULT_BLACKDUCK_SARIF_REPORT_FILE_PATH
                 .concat(ApplicationConstants.SARIF_REPORT_FILENAME);
```

2024-02-23 09:51 UTC, jahid1209 commented on src/main/java/io/jenkins/plugins/synopsys/security/scan/global/ApplicationConstants.java
> +
Move this segment up, so that all the Blackduck related parameters are together.

2024-02-23 09:51 UTC, jahid1209 commented on pom.xml
> +    <changelist>-SIGQA3</changelist>
It should be `-SNAPSHOT`

2024-02-28 11:46 UTC, sadmananik commented
This feature is merged with https://github.com/jenkinsci/synopsys-security-scan-plugin/pull/35 into main

2024-02-28 11:46 UTC, closed without merging