Fixed cognitive complexity for SARIF code
jenkinsci/synopsys-security-scan-plugin pull request #90
Opened 2024-02-27 12:54 UTC by sadmananik

### Testing done

```[tasklist]
### Submitter checklist
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

2024-02-28 07:39 UTC, zaman-akib requested changes

2024-02-28 07:39 UTC, zaman-akib commented on src/main/java/io/jenkins/plugins/synopsys/security/scan/service/ScannerArgumentService.java
>      public Sarif prepareSarifObject(Set<String> securityProducts, Map<String, Object> scanParameters) {
Unit test is missing for this method

2024-02-28 07:39 UTC, zaman-akib commented on src/main/java/io/jenkins/plugins/synopsys/security/scan/service/ScannerArgumentService.java
> +    private void handleBlackDuck(Map<String, Object> scanParameters, Sarif sarif) {
We can return **Sarif** object from this method and making it public, unit test can be added to increase test coverage

2024-02-28 07:39 UTC, zaman-akib commented on src/main/java/io/jenkins/plugins/synopsys/security/scan/service/ScannerArgumentService.java
> +    private void handlePolaris(Map<String, Object> scanParameters, Sarif sarif) {
We can return **Sarif** object from this method and making it public, unit test can be added to increase test coverage

2024-02-28 07:39 UTC, zaman-akib commented on src/main/java/io/jenkins/plugins/synopsys/security/scan/global/Utility.java
> +    public static String getDefaultSarifReportFilePath(boolean isBlackDuckScan, boolean isPolarisDuckScan) {
Add unit tests for all the new methods (there are 4 including this) of this class

2024-03-06 11:27 UTC, zaman-akib approved these changes

2024-03-06 12:03 UTC, jahid1209 approved these changes

2024-03-06 12:05 UTC, merged